language: minimal
dist: bionic
sudo: false

script:
  - ./extra/publish.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - olympus_2207*.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
